version: '3'
services:
  db_server_3:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
    - net
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: products

  api_server_3:
    image: zambotti/products_service
    volumes:
    - service_data:/var/service
    ports:
    - 8083:8083
    depends_on:
    - db_server_3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
    - net

volumes:
  db_data:
  service_data:

networks:
  net:
    external: true