version: '3'
services:
  db_server_1:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
    - net
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: customer

  api_server_1:
    image: zambotti/customer_service
    volumes:
    - service_data:/var/service
    ports:
    - 8081:8081
    depends_on:
    - db_server_1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
    - net
       
volumes:
  db_data:
  service_data:

networks:
  net:
    external: true